In [17]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [18]:
path='iris.csv'
rd=pd.read_csv(path)
df=pd.DataFrame(rd)
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [19]:
outputs=df['Species'].values
outpts=np.array(outputs)
print(np.unique(outputs))

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [20]:
df=df.drop('Id',axis='columns')
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [21]:
#data Normalization
def norm(min,max,t):
  l=((t-min)/(max-min))
  return l 

x=df.columns
x=list(x)
x.pop(-1)
print(x)
for i in x:
  val=df[i].values
  val=np.array(val)
  val_min=np.min(val)
  val_max=np.max(val)
  for j in range(len(val)):
    t=df[i][j]
    l=norm(val_min,val_max,t)
    #to update values in a dataframe
    df.at[j,i]=l
df.head()




['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']


SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0       0.222222      0.625000       0.067797      0.041667  Iris-setosa
1       0.166667      0.416667       0.067797      0.041667  Iris-setosa
2       0.111111      0.500000       0.050847      0.041667  Iris-setosa
3       0.083333      0.458333       0.084746      0.041667  Iris-setosa
4       0.194444      0.666667       0.067797      0.041667  Iris-setosa

In [22]:
df1=df.where(df['Species']=='Iris-setosa')
df1=df1.dropna()
df1.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0       0.222222      0.625000       0.067797      0.041667  Iris-setosa
1       0.166667      0.416667       0.067797      0.041667  Iris-setosa
2       0.111111      0.500000       0.050847      0.041667  Iris-setosa
3       0.083333      0.458333       0.084746      0.041667  Iris-setosa
4       0.194444      0.666667       0.067797      0.041667  Iris-setosa

In [23]:
df2=df.where(df['Species']=='Iris-versicolor')
df2=df2.dropna()
df2.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
50       0.750000      0.500000       0.627119      0.541667  Iris-versicolor
51       0.583333      0.500000       0.593220      0.583333  Iris-versicolor
52       0.722222      0.458333       0.661017      0.583333  Iris-versicolor
53       0.333333      0.125000       0.508475      0.500000  Iris-versicolor
54       0.611111      0.333333       0.610169      0.583333  Iris-versicolor

In [24]:
df3=df.where(df['Species']=='Iris-virginica')
df3=df3.dropna()
df3.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
100       0.555556      0.541667       0.847458      1.000000  Iris-virginica
101       0.416667      0.291667       0.694915      0.750000  Iris-virginica
102       0.777778      0.416667       0.830508      0.833333  Iris-virginica
103       0.555556      0.375000       0.779661      0.708333  Iris-virginica
104       0.611111      0.416667       0.813559      0.875000  Iris-virginica

In [25]:
df1_train=df1[:40]
df1_test=df1[40:]
df2_train=df2[:40]
df2_test=df2[40:]
df3_train=df3[:40]
df3_test=df3[40:]



In [26]:

frames_test=[df1_test,df2_test,df3_test]

In [27]:
df_test=pd.concat(frames_test)
df_test.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
40       0.194444         0.625       0.050847      0.083333  Iris-setosa
41       0.055556         0.125       0.050847      0.083333  Iris-setosa
42       0.027778         0.500       0.050847      0.041667  Iris-setosa
43       0.194444         0.625       0.101695      0.208333  Iris-setosa
44       0.222222         0.750       0.152542      0.125000  Iris-setosa

In [28]:
training=[df1_train,df2_train,df3_train]
mean_vector=[]
cov_matirx=[]
for i in training:
    i=pd.DataFrame(i)
    t=i.drop('Species',axis='columns')
    mean=t.mean()
    mean=list(mean)
    mean_vector.append(mean)
    cov=t.cov()
    cov=np.array(cov)
    cov_matirx.append(cov)

    

    


In [29]:
def gaussian(x, mean, cov):
    d = len(x)
    diff = x - mean
    exponent = -0.5 * np.dot(np.dot(diff.T, np.linalg.inv(cov)), diff)
    return (1.0 / ((2 * np.pi) ** (d / 2) * np.sqrt(np.linalg.det(cov)))) * np.exp(exponent)

In [30]:
outputs_test=df_test["Species"].values
outputs_test

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica'], dtype=object)

In [31]:
df_test=df_test.drop('Species',axis='columns')
df_test=np.array(df_test)
df_test=list(df_test)
df_test

[array([0.19444444, 0.625     , 0.05084746, 0.08333333]),
 array([0.05555556, 0.125     , 0.05084746, 0.08333333]),
 array([0.02777778, 0.5       , 0.05084746, 0.04166667]),
 array([0.19444444, 0.625     , 0.10169492, 0.20833333]),
 array([0.22222222, 0.75      , 0.15254237, 0.125     ]),
 array([0.13888889, 0.41666667, 0.06779661, 0.08333333]),
 array([0.22222222, 0.75      , 0.10169492, 0.04166667]),
 array([0.08333333, 0.5       , 0.06779661, 0.04166667]),
 array([0.27777778, 0.70833333, 0.08474576, 0.04166667]),
 array([0.19444444, 0.54166667, 0.06779661, 0.04166667]),
 array([0.33333333, 0.25      , 0.57627119, 0.45833333]),
 array([0.5       , 0.41666667, 0.61016949, 0.54166667]),
 array([0.41666667, 0.25      , 0.50847458, 0.45833333]),
 array([0.19444444, 0.125     , 0.38983051, 0.375     ]),
 array([0.36111111, 0.29166667, 0.54237288, 0.5       ]),
 array([0.38888889, 0.41666667, 0.54237288, 0.45833333]),
 array([0.38888889, 0.375     , 0.54237288, 0.5       ]),
 array([0.5277

In [32]:
def prediction(r):
    x=''
    if(r==0):
        x='Iris-setosa'
    elif(r==1):
        x='Iris-versicolor'
    elif(r==2):
        x='Iris-virginica' 
    return x
def check(r1,r2):
    acc=0
    for i,j in zip(r1,r2):
        if(i==j):
            acc+=1 
    leng=len(r1)
    return (acc/leng)*100

def check_class(r1,r2):
    acc=[]
    for j in range(3):
        x1=r1[10*j:10*(j+1)]
        x2=r2[10*j:10*(j+1)]
        acc_e=0
        for i,k in zip(x1,x2):
            if(i==k):
                acc_e+=1 
        leng=len(x1)
        t=acc_e/leng 
        t*=100
        acc.append(t)
    return acc[0],acc[1],acc[2]
def discrminant(a):
    c=a
    return np.log(c)

    

p=1/3
predictions=[]
discrimininant=[]
for i in range(len(df_test)):
    distri=[]
    for j in range(3):
        t=gaussian(df_test[i],mean_vector[j],cov_matirx[j])
        t*=p 
        distri.append(t)
    r=np.argmax(distri)
    dis=discrminant(distri[r])
    discrimininant.append(dis)
    pred=prediction(r)
    predictions.append(pred)
acc=check(predictions,outputs_test)
t1,t2,t3=check_class(predictions,outputs_test)
print("Accuracy of the classifer is:",acc)
print("Accuracy of the classifer of setsosa class is:",t1)
print("Accuracy of the classifer of versicolor class is:",t2)
print("Accuracy of the classifer of virginica class is:",t3)
print("Discriminant function:")
for i in discrimininant:
    print(i)



        


Accuracy of the classifer is: 100.0
Accuracy of the classifer of setsosa class is: 100.0
Accuracy of the classifer of versicolor class is: 100.0
Accuracy of the classifer of virginica class is: 100.0
Discriminant function:
5.763843958267506
-2.60594841893787
4.531907535421721
-1.4771867112190573
1.4083483274431199
4.841928147860276
4.815372604509148
5.903085207521731
6.111515734074053
6.488422141677577
2.2842229138285033
4.602289898856423
5.075645339594718
2.707052780746258
4.911390133970794
2.9909771768569016
4.7054196920867755
5.037306755167896
-0.9807639221968865
5.08945936554725
2.9218374796525097
-1.450989777380969
3.61226682177569
3.7376859733927215
2.5050309222876948
1.0224032745923126
2.07527808321945
3.658531211392288
2.3580185908774483
3.180256801968473
