In [3]:
#Question 1
import numpy as np
import pandas as pd
import seaborn as sns
from scipy.linalg import inv
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
path='/content/drive/MyDrive/Colab Notebooks/CS21B2028/PR ML Lab/datasets/'
df=pd.read_csv(path+'iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [5]:
x=df['Species'].unique()
print(x)

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [8]:
df1=df.where(df['Species']=='Iris-setosa')
df1=df1.dropna()
df1.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0  1.0            5.1           3.5            1.4           0.2  Iris-setosa
1  2.0            4.9           3.0            1.4           0.2  Iris-setosa
2  3.0            4.7           3.2            1.3           0.2  Iris-setosa
3  4.0            4.6           3.1            1.5           0.2  Iris-setosa
4  5.0            5.0           3.6            1.4           0.2  Iris-setosa

In [9]:
df2=df.where(df['Species']=='Iris-versicolor')
df2=df2.dropna()
df2.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
50  51.0            7.0           3.2            4.7           1.4   
51  52.0            6.4           3.2            4.5           1.5   
52  53.0            6.9           3.1            4.9           1.5   
53  54.0            5.5           2.3            4.0           1.3   
54  55.0            6.5           2.8            4.6           1.5   

            Species  
50  Iris-versicolor  
51  Iris-versicolor  
52  Iris-versicolor  
53  Iris-versicolor  
54  Iris-versicolor

In [10]:
df3=df.where(df['Species']=='Iris-virginica')
df3=df3.dropna()
df3.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
100  101.0            6.3           3.3            6.0           2.5   
101  102.0            5.8           2.7            5.1           1.9   
102  103.0            7.1           3.0            5.9           2.1   
103  104.0            6.3           2.9            5.6           1.8   
104  105.0            6.5           3.0            5.8           2.2   

            Species  
100  Iris-virginica  
101  Iris-virginica  
102  Iris-virginica  
103  Iris-virginica  
104  Iris-virginica

In [11]:
import random
r=df1['Id'].values
r=list(r)
test_1=random.choice(r)
df_t1=df1.where(df1['Id']==test_1)
df1=df1.drop(test_1-1)
print(df1.shape)
df_t1=df_t1.dropna()
df_t1

(49, 6)


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
11  12.0            4.8           3.4            1.6           0.2   

        Species  
11  Iris-setosa

In [12]:
r=df2['Id'].values
r=list(r)
test_2=random.choice(r)
print(test_2)
df_t2=df2.where(df2['Id']==test_2)
df2=df2.drop(test_2-1)
print(df2.shape)
df_t2=df_t2.dropna()
df_t2

85.0
(49, 6)


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
84  85.0            5.4           3.0            4.5           1.5   

            Species  
84  Iris-versicolor

In [13]:
r=df3['Id'].values
r=list(r)
test_3=random.choice(r)
print(test_3)
df_t3=df3.where(df3['Id']==test_3)
df3=df3.drop(test_3-1)
print(df3.shape)
df_t3=df_t3.dropna()
df_t3

145.0
(49, 6)


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
144  145.0            6.7           3.3            5.7           2.5   

            Species  
144  Iris-virginica

In [14]:
m1=df1.mean()
m2=df2.mean()
m3=df3.mean()
print(m1,m2,m3)

Id               25.775510
SepalLengthCm     5.010204
SepalWidthCm      3.418367
PetalLengthCm     1.461224
PetalWidthCm      0.244898
dtype: float64 Id               75.306122
SepalLengthCm     5.946939
SepalWidthCm      2.765306
PetalLengthCm     4.255102
PetalWidthCm      1.322449
dtype: float64 Id               125.102041
SepalLengthCm      6.585714
SepalWidthCm       2.967347
PetalLengthCm      5.548980
PetalWidthCm       2.016327
dtype: float64


<ipython-input-14-af32381eb627>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  m1=df1.mean()
<ipython-input-14-af32381eb627>:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  m2=df2.mean()
<ipython-input-14-af32381eb627>:3: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  m3=df3.mean()


In [15]:
c1=df1.cov()
c2=df2.cov()
c3=df3.cov()
print(c1,c2,c3)

                       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Id             213.052721      -0.235162     -0.383291       0.176531   
SepalLengthCm   -0.235162       0.125935      0.102309       0.017071   
SepalWidthCm    -0.383291       0.102309      0.148197       0.011977   
PetalLengthCm    0.176531       0.017071      0.011977       0.030340   
PetalWidthCm     0.126956       0.010574      0.011658       0.005944   

               PetalWidthCm  
Id                 0.126956  
SepalLengthCm      0.010574  
SepalWidthCm       0.011658  
PetalLengthCm      0.005944  
PetalWidthCm       0.011692                          Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Id             215.008503      -1.958418     -0.428741      -1.373469   
SepalLengthCm   -1.958418       0.265876      0.089579       0.189443   
SepalWidthCm    -0.428741       0.089579      0.099396       0.083202   
PetalLengthCm   -1.373469       0.189443      0.083202       0.224192   
PetalWidthCm    

<ipython-input-15-26ecaceb35c7>:1: FutureWarning: The default value of numeric_only in DataFrame.cov is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  c1=df1.cov()
<ipython-input-15-26ecaceb35c7>:2: FutureWarning: The default value of numeric_only in DataFrame.cov is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  c2=df2.cov()
<ipython-input-15-26ecaceb35c7>:3: FutureWarning: The default value of numeric_only in DataFrame.cov is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  c3=df3.cov()


In [16]:
m1=list(m1)
m2=list(m2)
m3=list(m3)
print(m1,m2,m3)

[25.775510204081634, 5.010204081632653, 3.4183673469387754, 1.4612244897959183, 0.24489795918367344] [75.3061224489796, 5.946938775510204, 2.7653061224489797, 4.255102040816326, 1.3224489795918366] [125.10204081632654, 6.5857142857142845, 2.9673469387755103, 5.548979591836735, 2.0163265306122446]


In [17]:
r1=df1.iloc[0]
x1=r1.values
x1=list(x1)
x1.remove('Iris-setosa')
print(x1)

[1.0, 5.1, 3.5, 1.4, 0.2]


In [18]:
r2=df2.iloc[0]
x2=r2.values
x2=list(x2)
x2.remove('Iris-versicolor')
print(x2)

[51.0, 7.0, 3.2, 4.7, 1.4]


In [19]:
r3=df3.iloc[0]
x3=r3.values
x3=list(x3)
x3.remove('Iris-virginica')
print(x3)

[101.0, 6.3, 3.3, 6.0, 2.5]


In [20]:
c1=np.array(c1)
c2=np.array(c2)
c3=np.array(c3)
print(c1,c2,c3)

[[ 2.13052721e+02 -2.35161565e-01 -3.83290816e-01  1.76530612e-01
   1.26955782e-01]
 [-2.35161565e-01  1.25935374e-01  1.02308673e-01  1.70705782e-02
   1.05739796e-02]
 [-3.83290816e-01  1.02308673e-01  1.48197279e-01  1.19770408e-02
   1.16581633e-02]
 [ 1.76530612e-01  1.70705782e-02  1.19770408e-02  3.03401361e-02
   5.94387755e-03]
 [ 1.26955782e-01  1.05739796e-02  1.16581633e-02  5.94387755e-03
   1.16921769e-02]] [[ 2.15008503e+02 -1.95841837e+00 -4.28741497e-01 -1.37346939e+00
  -5.32015306e-01]
 [-1.95841837e+00  2.65875850e-01  8.95790816e-02  1.89443027e-01
   5.89243197e-02]
 [-4.28741497e-01  8.95790816e-02  9.93962585e-02  8.32015306e-02
   4.12117347e-02]
 [-1.37346939e+00  1.89443027e-01  8.32015306e-02  2.24192177e-01
   7.37372449e-02]
 [-5.32015306e-01  5.89243197e-02  4.12117347e-02  7.37372449e-02
   3.92772109e-02]] [[ 2.08843537e+02 -1.65178571e-01  4.92984694e-01 -1.73843537e+00
  -4.75340136e-02]
 [-1.65178571e-01  4.12500000e-01  9.49404762e-02  3.09255952e-

In [21]:
from scipy.linalg import inv
def mahalobis_distance(x,c,m):
    sub=np.subtract(x,m)
    subt=sub.T
    C1=inv(c)
    d=np.sqrt(np.dot(np.dot(subt,C1),sub))
    return d
x_t=[x1,x2,x3]
c_t=[c1,c2,c3]
m_t=[m1,m2,m3]
#Calculating for setsosa
d=[]
classes=['Iris-setosa' ,'Iris-versicolor', 'Iris-virginica']
for z in range(len(x_t)):
    d=[]
    for i,j in zip(c_t,m_t):
        dis=mahalobis_distance(x_t[z],i,j)
        d.append(dis)
    d=np.array(d)
    t=z+1
    print(f"Mahalobis distance for {t} sample")
    print(d)
    r=np.argmin(d)
    r=int(r)
    print("predicted class:",classes[r])
    print("original class:",classes[z])
    print("\n")

Mahalobis distance for 1 sample
[ 1.75410875 12.47869459 19.95734761]
predicted class: Iris-setosa
original class: Iris-setosa


Mahalobis distance for 2 sample
[20.56649998  2.78121354  8.98445146]
predicted class: Iris-versicolor
original class: Iris-versicolor


Mahalobis distance for 3 sample
[30.51808224  7.57488742  3.16292544]
predicted class: Iris-virginica
original class: Iris-virginica


